#language: php
#dist: trusty
#php:
#- 5.5
#- 5.4
#- hhvm
#script: phpunit Test.php
env:
  global:
  - name="vishal"


language: java
jdk:
- oraclejdk7
script: 
  - javac FirstJavaProgram.java
  - java FirstJavaProgram
        
after_script: # here's a build step block
  - echo "We can put normal shell commands here"
  - echo "more shell commands here"
  - pwd
  - ls -l
  - echo "hiii"
  - echo "Bye"
  - echo $name